build:
  environment:
    NETLIFY_USE_PYTHON: "false"
    NETLIFY_USE_GO: "false"
    NETLIFY_USE_YARN: "false"
    NETLIFY_USE_PNPM: "false"
    NETLIFY_USE_RUBY: "false"
    NODE_ENV: "production"
    NODE_VERSION: "18"