[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_GO = "false"
  NETLIFY_USE_RUBY = "false"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_GO_INSTALL = "true"
  CI = "false"
  PYTHON_VERSION = "off"
  MISE_PYTHON_COMPILE = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist/client"
  autoLaunch = true
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200